### ISSUE TITLE
tracker模式可以启动，storage模式却不行，请问如何解决？

### ISSUE THREAD

**Issue by elvis-zhao** [ygqygq2/fastdfs-nginx#10]
启动命令：
docker run  --name my-nginx4 -p 9091:8888 -v D:\Materials:/var/fdfs ygqygq2/fastdfs-nginx storage

出错提示：
try to start the storage node...
ngx_http_fastdfs_set pid=14
tail: cannot open '/var/fdfs/logs/storaged.log' for reading: No such file or directory
tail: no files remaining

**Comment by ygqygq2** [comment]
你这是windows？最好使用 linux，我没试过 windows。

**Comment by fenggolang** [comment]
![image](https://user-images.githubusercontent.com/16982786/163777055-1968420a-4581-448e-b53e-90815bedf452.png)
