### ISSUE TITLE
通过docker-compose 启动storage节点失败

### ISSUE THREAD

**Issue by fenggolang** [ygqygq2/fastdfs-nginx#11]
![image](https://user-images.githubusercontent.com/16982786/163778196-31bafe27-85f3-4119-adfb-e85258cb0834.png)

**Comment by Sy9876** [comment]
see the entrypoint.sh,  I think stop server in func fdfs_start is not needed in container environment.
I comment out this line in entrypoint.sh:
`#fdfs_${FASTDFS_MODE}d /etc/fdfs/${FASTDFS_MODE}.conf stop`

**Comment by Sy9876** [comment]
modify entrypoint.sh：
```
TIMES=30
while [ ! -f "$PID_NUMBER" -a $TIMES -gt 0 ]
do
    sleep 1s
    TIMES=`expr $TIMES - 1`
done
```
change to    

```
TIMES=30
while [ ! -f "$FASTDFS_LOG_FILE" -a $TIMES -gt 0 ]
do
    sleep 1s
    TIMES=`expr $TIMES - 1`
done
```
