### ISSUE TITLE
容器 /usr/bin/start.sh 脚本有问题

### ISSUE THREAD

**Issue by Good0007** [ygqygq2/fastdfs-nginx#12]
无法替换配置文件内容
```shell
sed -i "s|group_name=.*$|group_name = ${GROUP_NAME}|g" 
# 应改为 
sed -i "s|group_name =.*$|group_name = ${GROUP_NAME}|g"

配置文件/etc/fdfs/storage.conf : group_name = 这里是有空格的！
```

**Comment by ygqygq2** [comment]
加不加空格都可以，主要是替换成功没，没成功的话，我优化下，让它有没有空格都支持。

**Comment by Good0007** [comment]
> 加不加空格都可以，主要是替换成功没，没成功的话，我优化下，让它有没有空格都支持。

没有替换成功，包括PORT替换，要么修改sed命令 要么就改下storage.conf。
另外 /etc/fdfs/mod_fastdfs.conf group_name 也需要替换，不然url访问资源400

**Comment by ygqygq2** [comment]
我看了下，你这个版本较老了。后面优化过了。你参考下master的，然后你自己dockerfile打个镜像就行。
