### ISSUE TITLE
启动tracker一直卡住不动

### ISSUE THREAD

**Issue by wangzd777** [ygqygq2/fastdfs-nginx#13]
![image](https://github.com/ygqygq2/fastdfs-nginx/assets/120180679/4e125808-9621-4e52-8248-6983627a376e)
启动tracker一直卡在这个地方。
启动命令如下：
docker run -dit --name tracker --restart=always  --network=fastdfs-net -v /home/docker/fastdfs/tracker:/var/fdfs ygqygq2/fastdfs-nginx tracker

镜像版本是最新的：
![image](https://github.com/ygqygq2/fastdfs-nginx/assets/120180679/8a013aa1-ed2b-4463-ae6d-02c8dc118843)

**Comment by wangzd777** [comment]
![image](https://github.com/ygqygq2/fastdfs-nginx/assets/120180679/2d8f7a8a-827d-44c0-8118-50945508cf71)
当上述 tracker无法启动的时候  storage 就一直无法启动成功。 22122的端口是已经开放了的

**Comment by ygqygq2** [comment]
你先不映射目录启动试试。
