### ISSUE TITLE
Error: 'No such process'

### ISSUE THREAD

**Issue by leschi** [ygqygq2/fastdfs-nginx#15]
Hello,

I am currently trying to run this Container in a Rancher / Kubernetes Cluster.
I get this error on both storage pods:
ngx_http_fastdfs_set pid=14
2024-01-05T08:23:45.747152878Z try to start the storage node...
2024-01-05T08:23:45.748247374Z kill pid: 22 fail, errno: 3, error info: No such process

Do you have any idea how to solve this?
Thanks a lot for your Help!

**Comment by ygqygq2** [comment]
You can turn off the health check, then go into the pod manually start to see what the reason is.
