### ISSUE TITLE
HTTP访问的问题

### ISSUE THREAD

**Issue by wenlinguo** [ygqygq2/fastdfs-nginx#3]
已经在docker中部署好了2个tracker和2个storage
目前遇到的问题，通过HTTP访问上传的图片 报错：

# 400 Bad Request
Your browser sent a request that this server could not understand. Sorry for the inconvenience.
Please report this message and include the following information to us.
Thank you very much!

URL: | http://IP:8080/pri/M00/00/00/rBj_31vG0_-AQfVwAAHJSSTHmco490.jpg?redirect=1
-- | --
Server: | izhp3if6v4fc4j7sz39y8dz
Date: | 2018/10/17 06:22:09

Powered by Tengine/2.2.2

**Comment by wenlinguo** [comment]
找到问题是 `mod_fastdfs.conf` 里面的 group_name 是默认的 没修改成我创建的 group_name

**Comment by ygqygq2** [comment]
@wenlinguo GROUP_NAME是通过环境变量传值进docker的，详细看下脚本`start.sh`，默认给了个`group1`组名。
