### ISSUE TITLE
无法在同一台宿主机上运行多个storage容器

### ISSUE THREAD

**Issue by zippenwang** [ygqygq2/fastdfs-nginx#5]
请问一下，在同一台docker的宿主机上运行多个storage容器，通过设置不同的端口号来区分，运行时，会出现storage节点之间无法同步，更准确的说，是storage节点之间无法连接，并且还会出现后启动的storage将之前的storage挤掉的现象，请问这是什么原因？

**Comment by ygqygq2** [comment]
你启动命令是怎么样的？
