### ISSUE TITLE
如何修改nginx端口

### ISSUE THREAD

**Issue by Heu1ty** [ygqygq2/fastdfs-nginx#6]
如何修改nginx的8080端口?

**Comment by Heu1ty** [comment]
> 如何修改nginx的8080端口?

我是通过docker-compose 启动的

**Comment by unicorn1009** [comment]
我也想知道如何修改端口, 我改了conf.d/storage.conf里面的8080, 但是重启容器后, 并不生效, 又被重置为8080了
