### ISSUE TITLE
tracker.conf文件中配置的storage怎么访问呢？这个配置文件我再tracker的docker中也没有发现有使用

### ISSUE THREAD

**Issue by swjsj** [ygqygq2/fastdfs-nginx#8]
# tracker.conf
upstream fdfs {
    server storage:8080;
}

server {
    listen       80 ;
    # server_name  _ ;

    location / {
        root   html;
        index  index.html index.htm;
        proxy_pass http://fdfs;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

}

**Comment by ygqygq2** [comment]
默认tracker里没有引用。你可以自己修改或者映射进去。
